name: Cherry-Pick Upstream commits
description: Cherry-pick upstream commits to a branch
inputs:
  repository:
    description: 'Repository to cherry-pick from'
    required: true
  upstream_repository:
    description: 'Upstream repository to cherry-pick from'
    required: true
  token:
    description: 'Personal Access Token to use for the target repository'
    required: true
runs:
  using: composite
  steps:
    - name: Partial Clone
      shell: bash
      run: |
        REPO="https://${GITHUB_ACTOR}:${{ inputs.token }}@github.com/${{ inputs.repository }}.git"
        git clone --filter=blob:none --sparse --depth 1 $REPO repo
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - name: Add upstream for repo
      shell: bash
      working-directory: repo
      run: |
        git remote add upstream ${{ inputs.upstream_repository }}
        git fetch upstream
    - name: Run Shell script
      shell: bash
      working-directory: repo
      run: script.sh
    - name: Push to branch
      shell: bash
      working-directory: repo
      run: |
        git push
