name: Sync Upstream changes Periodically

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository to sync from'
        required: true
        default: 'BlastLauncher/extensions'
      upstream_repository:
        description: 'Upstream repository to sync from'
        required: true
        default: https://github.com/raycast/extensions.git

  # schedule:
  #   # Sync changes hourly
  #   - cron: '0 * * * *'

jobs:
  sync_upstream:
    name: Sync Upstream changes
    runs-on: ubuntu-latest
    steps:
      - id: sync
        uses: BlastLauncher/actions/cherry-pick-upstream@main
        with:
          repository: ${{ inputs.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: ${{ inputs.upstream_repository }}
          commit_name: 'blastlauncher-bot[bot]'
          commit_email: '123755008+blastlauncher-bot[bot]@users.noreply.github.com'